Repository pulumi/pulumi-f5bigip, pull requests merged in 2019-06, with the labels that each got.

#10 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#11 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/cm/device.ts
  sdk/nodejs/cm/deviceGroup.ts
  sdk/nodejs/ltm/dataGroup.ts
  sdk/nodejs/ltm/iRule.ts
  sdk/nodejs/ltm/monitor.ts
  sdk/nodejs/ltm/node.ts
  sdk/nodejs/ltm/persistenceProfileCookie.ts
  sdk/nodejs/ltm/persistenceProfileDstAddr.ts
  sdk/nodejs/ltm/persistenceProfileSrcAddr.ts
  sdk/nodejs/ltm/persistenceProfileSsl.ts
  sdk/nodejs/ltm/policy.ts
  sdk/nodejs/ltm/pool.ts
  sdk/nodejs/ltm/poolAttachment.ts
  sdk/nodejs/ltm/profileFastHttp.ts
  sdk/nodejs/ltm/profileFastL4.ts
  sdk/nodejs/ltm/profileHttp.ts
  sdk/nodejs/ltm/profileHttp2.ts
  sdk/nodejs/ltm/profileHttpCompress.ts
  sdk/nodejs/ltm/profileOneConnect.ts
  sdk/nodejs/ltm/profileTcp.ts
  sdk/nodejs/ltm/snat.ts
  sdk/nodejs/ltm/snatPool.ts
  sdk/nodejs/ltm/virtualAddress.ts
  sdk/nodejs/ltm/virtualServer.ts
  sdk/nodejs/net/route.ts
  sdk/nodejs/net/selfIp.ts
  sdk/nodejs/net/vlan.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/sys/bigIpLicense.ts
  sdk/nodejs/sys/dns.ts
  sdk/nodejs/sys/iApp.ts
  sdk/nodejs/sys/ntp.ts
  sdk/nodejs/sys/provision.ts
  sdk/nodejs/sys/snmp.ts
  sdk/nodejs/sys/snmpTraps.ts
Labels: area/providers

#12 Update to released version, prepare release
  CHANGELOG.md
  go.mod
  go.sum
Labels: area/providers

#14 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#15 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
